# Generated by Django 5.1.5 on 2025-07-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_investmenttier_capital_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttier',
            name='name',
            field=models.CharField(choices=[('BUSINESS', 'Business'), ('PARTNERSHIP', 'Partnership'), ('TRADEMARK', 'Trademark'), ('VIP', 'Vip')], max_length=20, unique=True),
        ),
    ]
